name: cia_flutter
description: CIA Flutter Application

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.2



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  audioplayers: ^0.10.1
  flutter_launcher_icons: "^0.6.1"

flutter_icons:
  image_path: "icon/icon.png"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^0.12.0+1



# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/ic_thumb_11.png
    - assets/images/avengers.png
    - assets/images/ic_thumb_12.png
    - assets/images/ic_thumb_13.png
    - assets/images/ic_thumb_21.png
    - assets/images/ic_thumb_31.png
    - assets/images/ic_thumb_41.png
    - assets/images/movie_banner_1.png
    - assets/images/movie_banner_2.png
    - assets/images/movie_banner_3.png
    - assets/images/movie_banner_4.png
    - assets/images/logo.png
    - assets/images/powered_by.png
    - assets/images/ic_preview_1.png
    - assets/images/ic_preview_2.png
    - assets/images/ic_preview_3.png
    - assets/images/ic_preview_4.png
    - assets/images/logocia.png
    - assets/images/av.jpg

    - assets/images/vv.png
    - assets/images/project.png
    - assets/images/events.png
    - assets/images/forum.png
    - assets/images/comp.png
    - assets/images/avengers.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
