String SPLASH_SCREEN='SPLASH_SCREEN';
String PROJECT_LIST='PROJECT_LIST';
String HOME_SCREEN='HOME_SCREEN';
String ITEM_DETAILS_SCREEN='ITEM_DETAILS_SCREEN';
String GRID_ITEM_DETAILS_SCREEN='GRID_ITEM_DETAILS_SCREEN';